# The protonation state of the ligand can be easily generated by maestro, however in most cases the results still require manual inspection to ensure correctness.
ligprep -isd GNP.sdf -osd GNP_ph8.sdf -ph 8


### documentation
# muwang@GPCR:~$  ~/opt/schrodinger2020-3/ligprep -h
# usage: ligprep [options] (-ismi|-icsv|-imae|-isd) infile (-osd|-omae) outfile
# 
# General:
#   -h, -help             Print brief help message.
#   -long_help            Print exhaustive help message.
#   -inp <filename>       Read arguments from the supplied input file.
#   -sif_docs             List supported simplified input file format (SIF)
#                         keywords.
# 
# Ionization:
#   -epik                 Use Epik for ionization and tautomerization
#                         (Recommended, overrides -i).
#   -emb, -epik_metal_binding
#                         Run Epik with the metal_binding option so that states
#                         appropriate for interactions with metal ions in
#                         protein binding pockets are also generated.
#   -i {0,1,2}            Ionization treatment: 0 - do not neutralize or ionize,
#                         1 - neutralize only, 2 - neutralize and ionize
#                         (Default: 1). Note that -epik option overrides -i and
#                         always implies ionization and tautomerization.
#   -ph <number>          Effective/target pH.
#   -pht <number>         pH tolerance for generated structures.
# 
# Stereoisomers:
#   -ac                   Do not respect existing chirality properties and do
#                         not respect chiralities from the input geometry.
#                         Generate stereoisomers for all chiral centers up to
#                         the number permitted (specified using the -s option).
#                         This is equivalent to "Generate all combinations" in
#                         the Ligand Preparation user interface. Default
#                         behavior is to respect only explicitly indicated
#                         chiralities.
#   -g                    Respect chiralities from input geometry when
#                         generating stereoisomers.
#   -s #                  Generate up to this many (#) stereoisomers per input
#                         structure. (Default: 32).
# 
# Force-field based geometry optimization:
#   -bff {14,16}          Force-field to be used for the final geometry
#                         optimization. Default: 14 (OPLS_2005). For OPLS3e
#                         specify 16.
# 
# Standard and job control options:
#   -NJOBS NJOBS          Divide the overall job into NJOBS subjobs.
#   -NSTRUCTS NSTRUCTS    Divide the overall job into subjobs with no more than
#                         NSTRUCTS structures.
#   -HOST <hostname>      Run job remotely on the indicated host entry.
#   -WAIT                 Do not return a prompt until the job completes.
#   -LOCAL                Do not use temporary directory for job files. Keep
#                         files in the current directory.
# 
# Typical usage:
#   Sample protonation states and stereoisomers, optimize geometry
#   using OPLS force-field, and store results in Maestro format:
# 
#     ligprep <input> -omae outfile.maegz -epik
# 
#   where <input> is one of:
#     -ismi infile.smi
#     -icsv infile.csv
#     -isd  infile.sd
#     -imae infile.mae
