# The protonation state of the ligand can be easily generated by maestro, however in most cases the results still require manual inspection to ensure correctness.
ligprep -isd GNP.sdf -osd GNP_ph8.sdf -ph 8
